### ISSUE TITLE
Mapping entries split across newlines cause incorrect parse results

### ISSUE THREAD

**Issue by stephenwhittle** [fktn-k/fkYAML#288]
### Description

Parsing a block mapping where a mapping entry is split across two lines incorrectly results in the entry's string value being parsed as a mapping entry (with null value) itself. 

I believe this is because the check at `lexical_analyzer.hpp:120-127` incorrectly assumes that a key-value pair must contain the value on the same line as the key, resulting in the `: ` token being treated as a block mapping prefix and in turn causing the node containing `stringValue` to be created as a mapping entry in an implicit mapping value by the switch case at `deserializer.hpp:257`.

If I am interpreting the specification correctly, 8.2 in the YAML spec suggests that the lexer should be using a larger look-ahead to scan for the presence of `: ` on the line containing `stringValue` to distinguish between a scalar value and the key of a mapping entry/key-value pair or sequence entry.

 The implementation already handles the sequence entry case, because the indicator for a sequence entry is the next token, so the check at `deserializer.hpp:263` doesn't require any additional lookahead. 

Because the indicator for a key-value pair occurs *after* the string value, I believe this implies the lexer will need to be extended to internally handle the lookahead so that it can properly distinguish between scalars and mapping entry keys, or else expose functionality so that the deserializer can perform the lookahead and decide whether to create the child node as a mapping or as a string/scalar value.

### Reproduction steps

The following minimal fragment is parsed incorrectly:
```
key: 
    stringValue
```

### Expected vs. actual results

`stringValue` should be parsed as a scalar string, but is instead parsed as a mapping entry with a null value. 

### Compiler and operating system

VS 2022 (both clang-cl and msvc compilers), Win 10

### Library version

d77e7f58b68970b6a12c67dde6e2569863bc7328

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/fktn-k/fkYAML/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/fktn-k/fkYAML#how-to-execute-the-unit-tests).

**Comment by fktn-k** [comment]
@stephenwhittle   
Thanks for sharing the issue.  

I'm sure that the implementation isn't covering such cases enough to determine a following scalar to be either a key or a value after a block mapping key.  

So, I agree with your suggestion that either the parser or the lexer should do the look-ahead.  
In my opinion, the parser should do that because I don't want the lexer to do too much beyond distinguishing a valid token from another.  
Although you might noticed that the lexer is determining whether a colon indicates either a child mapping entry or a value associated with the last key, that should be done in the parser too.  

I'll try to fix it.  
Until the fix is available, as a workaround, the issue should be resolved by putting the `stringValue` on the same line as the key.

**Comment by fktn-k** [comment]
@stephenwhittle   
I've fixed the reported issue in the PR #289.  
Could you please confirm the changes in the latest develop branch?

**Comment by stephenwhittle** [comment]
Very fast work, thank you! I can confirm this resolves the issue.
