### ISSUE TITLE
too few template aruments

### ISSUE THREAD

**Issue by Michael-Lafreniere** [fktn-k/fkYAML#357]
### Description

Just including the node.hpp file (nothing else) generates two errors in visual studio 2022 Version 17.10.1.

The first one: error C2976: 'fkyaml::v0_3_8::node_value_converter': too few template arguments
The second one: error C2955: 'fkyaml::v0_3_8::node_value_converter': use of class template requires template argument list

I verified this by just downloading the standalone header into a project that compiles cleanly and adding the node.hpp file into its source files, then including it.

### Reproduction steps

#include <fkYAML/node.hpp>

### Expected vs. actual results

I expected it to compile cleanly when merely including the header file(s).

### Error messages

```Shell
error C2976: 'fkyaml::v0_3_8::node_value_converter': too few template arguments
error C2955: 'fkyaml::v0_3_8::node_value_converter': use of class template requires template argument list
```

### Compiler and operating system

Windows 10, Visual Studios 2022 version 17.10.1

### Library version

0.3.8

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/fktn-k/fkYAML/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/fktn-k/fkYAML#how-to-execute-the-unit-tests).

**Comment by Michael-Lafreniere** [comment]
The previous project was was compiled with C++20.

I just created a brand new console project using all the default settings.  I downloaded https://github.com/fktn-k/fkYAML/blob/develop/single_include/fkYAML/node.hpp directly into the folder and tried to compile it.

node.hpp(8668,9): error C2976: 'fkyaml::v0_3_8::node_value_converter': too few template arguments
node.hpp(8668,27): error C2955: 'fkyaml::v0_3_8::node_value_converter': use of class template requires template argument list

Unless I'm missing something big here?  The single header should work standalone without having to clone the project correct (I want the whole thing I'm just testing right now since mine worked fine 3 days ago, but when I updated it broke.)

**Comment by fktn-k** [comment]
@Michael-Lafreniere   
As you mentioned, the single header should work if it's compiled with C++11 or newer.  
Thanks to your additional information mentioned C++ standard, however, I've realized that Windows builds with C++20 haven't been tested both in my local environment and the GitHub Actions workflows.  
So I tested builds with Visual Studio 2022 and C++20 and the reported errors are related to building fkYAML with C++20 (and newer).  

Although I can't tell what the root cause is, building fkYAML on Windows with C++20 or newer somehow ignores the default template parameter for node_value_converter and the compiler emits the errors.  
So I've made a quick fix in [this](https://github.com/fktn-k/fkYAML/tree/fix_too_few_template_arguments) branch for the errors as well as some other warniings when compiled with C++17 or older without the `/permissive-` flag.  
Can you download and use this standalone [node.hpp](https://github.com/fktn-k/fkYAML/blob/fix_too_few_template_arguments/single_include/fkYAML/node.hpp) file to check if the errors are resolved?

**Comment by Michael-Lafreniere** [comment]
Yes, that fixed it in both the quick test I put together and my other two projects.  Awesome work and thank you for the fast replies!

**Comment by fktn-k** [comment]
@Michael-Lafreniere   
Thanks for the confirmation.  
FYI, I just merged the branch I shared above into develop.
